packadd! dracula
syntax enable
colorscheme dracula
set encoding=utf-8

" Tab and space
set ts=4
set sw=4
set tw=0
set expandtab

" Whitespace
set listchars=tab:→\ ,eol:¬,nbsp:␣,trail:•,extends:⟩,precedes:⟨
set list